{
 "title": "ElasticSearch",
 "tags": [
  "infra",
  "b2c",
  "elastic"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"$cluster\"}) + scalar(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"$cluster\"}) * 2 + scalar(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"$cluster\"}) * 3"
      }
     ]
    },
    {
     "title": "Running Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Active Data Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Pending Tasks",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Active Primary Shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Initializing Shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Relocating Shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Unassigned Shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Delayed Unassigned Shards",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Documents indexed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{cluster=~\"$cluster\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{cluster=~\"elasticsearch\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Queris/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{type}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemFree{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\", type!=\"management\"}[5m])",
     "legendFormat": "{{ name }} {{ type }}"
    }
   ]
  },
  {
   "title": "Avg. CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(irate(node_cpu{cluster=~\"$cluster\"}[10s])) by(mode) *100",
     "legendFormat": "{{ mode }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"elasticsearch\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"elasticsearch\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "RX/TX Rate 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_transport_rx_packets_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(elasticsearch_transport_tx_packets_total{cluster=~\"$cluster\"}[5m])) * -1",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ name }} {{ gc }}"
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Disk Available",
   "type": "graph",
   "description": "free / total",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_filesystem_data_free_bytes{name=~\"elasticsearch-(master|data)-.*\"}/elasticsearch_filesystem_data_size_bytes{name=~\"elasticsearch-(master|data)-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "elasticsearch_os_load1", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Health Alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"elastic.*\"}) + scalar(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"elastic.*\"}) * 2 + scalar(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"elastic.*\"}) * 3"
    }
   ]
  }
 ]
}