---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: elasticsearch-exporter
          image: "justwatch/elasticsearch_exporter:1.1.0rc1"
          imagePullPolicy: IfNotPresent
          args: [ "--es.uri=http://elasticsearch-client.elasticsearch:9200",
                  "--es.all",
                  "--es.indices",
                  "--es.timeout=30s",
                  "--web.listen-address=:9108",
                  "--web.telemetry-path=/metrics"]
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources:
            {}
            
          ports:
            - containerPort: 9108
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
      volumes:


---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9108
      protocol: TCP
  selector:
    app: elasticsearch-exporter
