apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: secret-staging-demo
  # Change this to your own domain
  commonName: staging.demo.example.net
  dnsNames:
  # Change this to your own domain
  - staging.demo.example.net
  issuerRef:
    name: issuer
    kind: Issuer
  acme: null
