version: '3'
services:
  openresty:
    image: openresty/openresty:alpine-fat
    environment:
      - MY_ENV=rammusxu
    volumes:
      # - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./conf.d/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports: 
    - "80:80"