site_url: https://rammusxu.github.io/
site_author: Rammus Xu
site_description: It's Rammus Toolkit. A collection of snippets, examples and solutions.
site_name: Rammus Toolkit

repo_url: https://github.com/RammusXu/toolkit

theme: 
  name: material
  logo:
    icon: 'build'
  language: 'zh-TW'

  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - rust
  #   - python
  #   - bash
  #   - js

markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/#types
  - toc:
      permalink: true

copyright: |
  Copyright © 2015- Rammus Xu
  All website licensed under CC BY-SA 4.0

extra:
  social:
    - type: 'github'
      link: 'https://github.com/rammusxu'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/rammusxu'

google_analytics:
  - 'UA-67048750-3'
  - 'auto'

plugins:
  - search
  # - minify:
  #     minify_html: true
