site_url: https://rammusxu.github.io/toolkit
site_author: Rammus Xu
site_description: It's Rammus Toolkit. A collection of snippets, examples and solutions.
site_name: Rammus Toolkit

repo_url: https://github.com/RammusXu/toolkit

theme: 
  name: material
  icon:
    logo: fontawesome/solid/toolbox
  language: 'en'

markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>
  <br> Copyright © 2015- Rammus Xu
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rammusxu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rammusxu
  disqus: rammusxu

google_analytics:
  - 'UA-67048750-3'
  - 'auto'

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
