version: '3'
services:
  frontend:
    image: openresty/openresty:alpine-fat
    environment:
      - MY_ENV=rammusxu
    volumes:
      # - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./front-conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports: 
    - "8001:80"
  backend:
    image: openresty/openresty:alpine-fat
    environment:
      - MY_ENV=rammusxu
    volumes:
      # - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./back-conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports: 
    - "8002:80"