{
 "title": "Benchmark",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "TTFB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(\n  0.5,\n  {job=\"benchmark\"} |= \"target\" | logfmt | unwrap ttfb [1m]\n) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(\n  0.5,\n  {job=\"benchmark\"} |= \"target\" | logfmt | unwrap speedDownload [1m]\n) by (target) * 8",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Connect Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(\n  0.5,\n  {job=\"benchmark\"} |= \"target\" | logfmt | unwrap connect [1m]\n) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(\n  0.5,\n  {job=\"benchmark\"} |= \"target\" | logfmt | unwrap totalTime [1m]\n) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}