server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/shared_logs/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: benchmark
  static_configs:
  - targets:
      - loki
    labels:
      job: benchmark
      __path__: /var/shared_logs/busybox
