apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox2
spec:
  dnsConfig:
    options:
      - name: single-request-reopen
  containers:
  # - image: busybox
  - image: alpine:3.11
    command:
      - tail
      - -f
      - /dev/null
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never