apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: selfsigned-clusterissuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: aliyun-edge
  namespace: default
spec:
  secretName: aliyun-edge-tls
  issuerRef:
    # The issuer created previously
    kind: ClusterIssuer
    name: selfsigned-clusterissuer
  commonName: aliyun.edge
