apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mtls-server-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    targetPort: http
  selector:
    app: mtls-server
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mtls-server
spec:
  ports:
  - name: http
    port: 443
    targetPort: http
  selector:
    app: mtls-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      volumes:
      - name: config
        configMap:
          name: mtls-server-config
      - name: aliyun-edge-tls
        secret:
          secretName: ali-tls
      containers:
      - name: openresty
        image: openresty/openresty:1.15.8.2-1-alpine
        ports:
        - name: http
          containerPort: 443
        volumeMounts:
        - name: config
          subPath: nginx.conf
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          readOnly: true
        - name: aliyun-edge-tls
          mountPath: /cert
          readOnly: true
        resources:
          limits:
            cpu: 1000m
            memory: 1G
          requests:
            cpu: 100m
            memory: 1G

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: mtls-server-config
data:
  nginx.conf: |-
    worker_processes            auto;

    events {
        worker_connections      65536;
        multi_accept            on;
        accept_mutex            off;
        use                     epoll;
    }

    http {

      log_format  main  '$remote_addr - $remote_user - $upstream_cache_status [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  logs/access.log  main;

      server_names_hash_bucket_size  128;

      # access_log                on;
      root                        /usr/share/nginx/html;
      sendfile                    on;
      tcp_nopush                  on;
      tcp_nodelay                 on;

      # client_max_body_size      10M;
      # https://blog.percy.io/tuning-nginx-behind-google-cloud-platform-http-s-load-balancer-305982ddb340
      keepalive_timeout         650;
      # keepalive_requests        10000;

      # GZIP support
      gzip                      on;
      gzip_disable              "msie6";
      gzip_min_length           128;
      gzip_vary                 off;
      gzip_proxied              any;
      gzip_comp_level           6;
      gzip_buffers              16 8k;
      gzip_types                text/css
                                text/plain
                                text/javascript
                                application/javascript
                                application/json
                                application/x-javascript
                                application/xml
                                application/xml+rss
                                application/xhtml+xml
                                application/x-font-ttf
                                application/x-font-opentype
                                application/vnd.ms-fontobject
                                image/svg+xml
                                image/x-icon
                                image/vnd.microsoft.icon
                                application/rss+xml
                                application/atom_xml
                                application/vnd.apple.mpegURL
                                application/x-mpegurl
                                vnd.apple.mpegURL
                                application/dash+xml;

      # upstream api {
      #   server                        api.default.svc.cluster.local;
      #   keepalive                     16;
      #   keepalive_requests            100000;
      # }

      # Enable persistent upstream connections
      proxy_http_version              1.1;
      proxy_set_header                Connection "";

      # Enable proxy caching
      proxy_cache_path                /var/cache/nginx levels=1:2 keys_zone=storage:128m inactive=10m max_size=64G;
      proxy_cache                     storage;
      proxy_cache_use_stale           updating;
      proxy_cache_background_update   on;
      proxy_cache_lock                on;
      proxy_cache_lock_age            1s;
      proxy_cache_lock_timeout        1s;


      server {
        listen      443 ssl;

        # Cluster healthchecks
        if ( $http_user_agent ~* (GoogleHC|Go\-http\-client|kube\-proxy) ) {
          return 200;
        }


        ssl_certificate        /cert/tls.crt;
        ssl_certificate_key    /cert/tls.key;
        ssl_client_certificate /cert/tls.crt;
        ssl_verify_client      on;

        location / {
            echo "hello $host";
        }
      }
    }
