apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard
  namespace: vpn
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Asia/Taipei"
  # PEERS: "2"
  SERVERURL: "1.1.1.1"
  SERVERPORT: "51820"
  PEERS: "rammus"
  # PEERDNS: "8.8.8.8"
  PEERDNS: "172.21.0.10" # kubedns service IP
  ALLOWEDIPS: "0.0.0.0/0, ::/0"


#   INTERNAL_SUBNET: "10.13.13.0"
  # wg0.conf: |-

  #   [Interface]
  #   Address = 10.4.0.12
  #   ListenPort = 51820
  #   PrivateKey = key
  #   PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  #   PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

  #   [Peer]
  #   # peer_rammus
  #   PublicKey = key
  #   AllowedIPs = 0.0.0.0/0
