apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcp-ingress
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: web-static-ip
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: helloweb-service
          servicePort: 8080
