kind: Service
apiVersion: v1
metadata:
  name: telepresence-rammus
spec:
  selector:
    owner: rammus
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepresence-rammus
spec:
  replicas: 1
  selector:
    matchLabels:
      owner: rammus
  template:
    metadata:
      labels:
        owner: rammus
    spec:
      containers:
      - name: telepresence
        image: datawire/telepresence-k8s-priv:0.99
        ports:
        - name: http
          containerPort: 80