apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: gclb-cdn-hp
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: gclb-cdn-hpq
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true