apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk-busybox
  namespace: default
  labels:
    app: wrk-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrk-busybox
  template:
    metadata:
      labels:
        app: wrk-busybox
    spec:
      initContainers:
      - name: wrk
        image: williamyeh/wrk:4.0.2
        args: 
        - -t10
        - -c500
        - -d30
        - --latency
        - http://10.4.1.6:3000
      containers:
      - name: busybox
        image: busybox
        args: 
        - sh
        - -c
        - |
          tail -f /dev/null
        
        