apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client
spec:
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      containers:
      - name: iperf3-client
        image: rammusxu/iperf3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/sh","-c"]
        args:
        - sleep infinity
