apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      # - name: iperf3
      #   image: rammusxu/iperf3
      #   resources:
      #     limits:
      #       memory: "128Mi"
      #       cpu: "500m"
      #   ports:
      #   - containerPort: 5201
      #     protocol: TCP
      #     name: tcp
      - name: iperf3-udp
        image: rammusxu/iperf3
        # args: ["-s", "-p", "5021"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5201
          protocol: UDP
          name: iperf3
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-udp
spec:
  type: NodePort
  selector:
    app: iperf3
  ports:
  - port: 5201
    targetPort: iperf3
    protocol: UDP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: iperf3
# spec:
#   selector:
#     app: iperf3
#   ports:
#   - port: 5201
#     targetPort: tcp
#     protocol: TCP
