apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: sysctl-vm
  labels:
    app: sysctl-vm
spec:
  selector:
    matchLabels:
      app: sysctl-vm
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "100%"
  template:
    metadata:
      labels:
        app: sysctl-vm
    spec:
      initContainers:
      - name: id
        image: busybox
        command: ["id"]
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262145"]
      - name: get-sysctl
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sysctl", "vm.max_map_count"]
      containers:
      - name: sleep
        image: swaglive/sleep
        imagePullPolicy: IfNotPresent
