apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: secret-demo
  renewBefore: 360h # 15d
  # Change this to your own domain
  commonName: demo.example.net
  dnsNames:
  # Change this to your own domain
  - demo.example.net
  issuerRef:
    name: issuer
    kind: Issuer
  acme:
    config:
    - http01:
        ingress: ingress
      domains:
      # Change this to your own domain
      - demo.example.net
