apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: ingress-nginx
  name: ingress-nginx-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress-nginx-controller
  targetCPUUtilizationPercentage: 50
  