
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec: 
        containers: 
          - name: docker-cmds 
            image: docker:19.03 
            command: ['docker', 'run', '-p', '80:80', 'httpd:latest'] 
            resources: 
                requests: 
                    cpu: 10m 
                    memory: 256Mi 
            env: 
              - name: DOCKER_TLS_VERIFY
                value: "1"
              - name: DOCKER_CERT_PATH
                value: /certs/client
            #   - name: DOCKER_HOST 
            #     value: tcp://localhost:2376
            volumeMounts: 
              - name: docker-cert-client
                mountPath: /certs/client
          - name: dind-daemon 
            image: docker:19.03-dind 
            resources: 
                requests: 
                    cpu: 20m 
                    memory: 512Mi 
            securityContext: 
                privileged: true 
            volumeMounts: 
              - name: docker-cert-client
                mountPath: /certs/client
        volumes: 
          - name: docker-cert-client
            emptyDir: {}