
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-no-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind-no-tls
  template:
    metadata:
      labels:
        app: dind-no-tls
    spec: 
        containers: 
          - name: docker-cmds 
            image: docker:19.03 
            command: ['docker', 'run', '-p', '80:80', 'httpd:latest'] 
            resources: 
                requests: 
                    cpu: 10m 
                    memory: 256Mi 
            env: 
              - name: DOCKER_HOST 
                value: tcp://localhost:2375
          - name: dind-daemon 
            image: docker:19.03-dind 
            env: 
              - name: DOCKER_TLS_CERTDIR
                value: ""
            resources: 
                requests: 
                    cpu: 20m 
                    memory: 512Mi 
            securityContext: 
                privileged: true 