name: Publish
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - mkdocs.yml
      - requirements.txt

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@9ed3b4354aa821831ba17a63c55caf73b23e6109
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
